// Reviewed visible text outside the masked regions of the supported banking surface.
export const bankImage = {
  mask: "input, select, .details td + td, .data-table tbody td, .intro, .training",
  text: [
    "N",
    "Northstar",
    "FEDERAL CREDIT UNION",
    "Training environment",
    "Member services",
    "Account servicing",
    "All records are synthetic",
    "MEMBER SERVICES",
    "INTERNAL WORKSPACE",
    "Member search",
    "Find a member",
    "Member number",
    "Exact member number required",
    "Search members",
    "Search results",
    "Member",
    "Status",
    "Action",
    "Member not found",
    "No member matched the supplied number.",
    "Return to search",
    "Member overview",
    "Membership details",
    "Membership status",
    "Accounts",
    "New sub-account",
    "Account",
    "Type",
    "Savings account not found",
    "This membership has no savings account.",
    "Savings account",
    "Account details",
    "Account type",
    "Available balance",
    "Currency",
    "Balance verified for this training session",
    "Back to member",
    "Account setup",
    "Account nickname",
    "Cancel",
    "Review account",
    "Review sub-account",
    "Prepared account",
    "Preparation status",
    "Edit details",
    "Open account",
    "Permission denied",
    "Your current servicing role cannot view this member.",
    "Application unavailable",
    "The servicing application could not load this record.",
    "Session expired",
    "Restore the training session to continue. No real credentials are required.",
    "Restore demo session",
    "Validation rejected",
    "The account details do not meet the servicing requirements.",
    "Return to account setup",
    "Service notice",
    "Account balances are current as of this session.",
    "Dismiss notice",
    "OPERATOR ACTION",
    "Operator acknowledgment",
    "A servicing notice requires review before continuing. Acknowledge this synthetic training notice to return to the member record.",
    "Acknowledge notice",
  ],
};
